# Generated by Django 4.2.7 on 2023-12-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect_Web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(),
        ),
    ]
